### ISSUE TITLE
Add Train Motor (#88011) as a Device

### ISSUE THREAD

**Issue by corneliusmunz** [sharpbrick/powered-up#104]

**Comment by corneliusmunz** [comment]
Discover Port 0. Receiving Messages ...
..........
Discover Ports Function: 9 / 9
##################################################
0B-00-43-00-01-01-01-00-00-01-00
05-00-43-00-02
12-00-44-00-00-00-4C-50-46-32-2D-54-52-41-49-4E-00-00
0E-00-44-00-00-01-00-00-C8-C2-00-00-C8-42
0E-00-44-00-00-02-00-00-C8-C2-00-00-C8-42
0E-00-44-00-00-03-00-00-C8-C2-00-00-C8-42
0B-00-44-00-00-04-00-00-00-00-00
08-00-44-00-00-05-00-18
0A-00-44-00-00-80-01-00-04-00
##################################################

**Comment by vuurbeving** [comment]
I took the liberty of creating a PR for this adding the train motor device.
