### ISSUE TITLE
Question: Move Hub FW 2.0.00.0017

### ISSUE THREAD

**Issue by Steffel** [sharpbrick/powered-up#170]
Hi, great project.
I tried to run an example for the (Boost-) Move Hub with Firmware 2.0.00.0017 but it didnt work - it seems to stop at
await expectedDevicesCompletedTask;
With my own code (.NET 5, WinRT) i could catch an advertisement and identify device, service and characteristics but could not set up a notification - failed with "Status unreachable".
Did you get your example code work for - say
example = new Example.ExampleMoveHubInternalTachoMotorControl();
?

Besides: A few days ago i got an answer from lego support that they will not publish the protocol for 51515 to "protect their products".

**Comment by Steffel** [comment]
I found the problem: Windows already paired with the device.
Removing it from the Bluetooth settings first made the example work.

**Comment by tthiery** [comment]
If you have any questions or suggestions, feel free to raise issues!

**Comment by Steffel** [comment]
I just wondered if the bluetooth protocol is able to give a hint that someone else has his "hands on the device" so it is possible to throw an appropriate exception. I had the above issue several days without any idea what is going wrong.

**Comment by tthiery** [comment]
Feel free to create a Pull Request 😀
