### ISSUE TITLE
CreateVirtualPort should await VirtualPort feedback and return port

### ISSUE THREAD

**Issue by tthiery** [sharpbrick/powered-up#38]

**Comment by Mattze0815** [comment]
Unermüdlich, der Mann… 😊

Ich hoffe, dass ich bald Zeit habe, einzusteigen. Heute habe ich eine neue Powered Up Einheit V46 mit einem „großen Technik Motor V46“ bekommen (für das Krokodil 10277).

Bin voller Vorfreude, das alles mit der .NET Bibliothek in Betrieb zu nehmen, aber momentan fehlt mir noch die Zeit. Ab Montag erst mal drei Wochen Urlaub mit der Familie…

Mit freundlichen Grüßen,
Matthias Runte

Dr. Matthias Runte
Treudelbergweg 13, 22397 Hamburg
Tel: +49 (40) 4327098-1, Fax -2
Mobil: +49 (175) 2227511




Von: T. Thiery <notifications@github.com>
Gesendet: Samstag, 4. Juli 2020 14:49
An: sharpbrick/powered-up <powered-up@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [sharpbrick/powered-up] CreateVirtualPort should await VirtualPort feedback and return port (#38)
