### ISSUE TITLE
Investigate Lessons Learnt from Vouzamo/Lego

### ISSUE THREAD

**Issue by tthiery** [sharpbrick/powered-up#47]
MIT licensed source code, found [here](https://github.com/Vouzamo/Lego)

**Comment by tthiery** [comment]
**Interesting**
- Focus on Routines (e.g. [RangeCalibrations](https://github.com/Vouzamo/Lego/blob/master/src/Lego/Lego.Core/Routines/RangeCalibrationRoutine.cs)) similar in vision than the Functions namespace here.
- Also focus on Technic Motors
- Implements a hub to device message forwarding similar where nathankellenicki/node-poweredup is heading to.
- Mixes device and ports 
- Also uses convenience interfaces on technic hub (like PortA/PortB)
- Implements named commands on (e.g.) motor as an extension

**Do not copy/regress**
- Uses Time based awaits to allow device to process message instead of awaiting response (e.g. for SetSingleInputMode)
- Partial Message parsing

**Lesson Learnt to consider**
- Hub owns a Queue for messages
- Uses CW and CCW abbreviation... SharpBrick.PowerdUP only uses +/- without defining them
- Guarding by capabilities of the device (e.g. input/output mode, combined modes support, etc)
- Init BLE connection by known hub ids
- Support multiple device connections at once (does SharpBrick.PoweredUp?)
- Usage of `netstandard2.0`. SharpBrick.PoweredUp uses `netstandard2.1` which essentially blocks adoptation by .NET Framework (forever) and UWP (till .NET 5 is out).

**Comment by tthiery** [comment]
@Vouzamo I took the liberty to analyze to analyze your library Vouzamo/Lego. Very interesting read. Many similar decisions and some interesting outcomes.

**Comment by Vouzamo** [comment]
This is great. I haven't been able to commit much time at all for the past few weeks but keen to contribute anything I can as my availability improves in the coming weeks.

Given that you have already surpassed the capabilities in my repo and addressed some of the deficiencies, I will treat it as a deprecated library / personal project and link to yours once I have time to update it.

Further development and enhancements can be to yours to avoid fragmentation / duplication etc. Let me know how you prefer contributions to work? PRs from feature branches or fork and PR from forked repo etc.

**Comment by tthiery** [comment]
@Vouzamo See https://github.com/sharpbrick/powered-up/blob/master/CONTRIBUTING.md

If you find something missing in the guide, just open an issue. Since open source and hobby projects like this live from collaboration and everyone's benefit, my goal will be to release Pull Requests quickly after merge. So as soon as there are contributions, I will keep the releases small and on the master branch.
