### ISSUE TITLE
Investigate usage of `netstandard2.0` with Span emulation on .NET Framework

### ISSUE THREAD

**Issue by tthiery** [sharpbrick/powered-up#53]
- [ ] check usage of WinRT on `netstandard2.0`
- [x] check usage of `Span<T>` on `netstandard2.0`
- [x] check compiling C# 8.0 feature usage

vs: This is a hobby project and I want to use C# x and .NET y features

Lesson Learnt from #47

**Comment by tthiery** [comment]
## Analysis regards C# Usage

- Index, Ranges, Span<T>, ValueTuple<T>, IAsyncEnumerable<T> could be polyfilled.
- Default Interface Methods are currently not utilized which are the only hard constraints for C# 8.0 incompatibility. Restricting usage of Direct Interface Method could make a trait like programming model impossible. However, there is currently no vision for something like that.

## Analysis regards using `netstandard2.0` instead of `netstandard2.1`

.NET Framework only implements `netstandard2.0`. Analyzed using the *.NET Portability Analyzer* many Span<T> library function (not the type itself) are missing (e.g. how to convert from Span<byte> to Int32). As of v2.0 roughly 11% of the function calls are not compatible.

**Comment by tthiery** [comment]
This library will **not be supported** on .NET Framework 4.8.

**Rationale**

- .NET Core 3.1 supports WinForms and WPF applications.
- The .NET Framework (4+) is with latest with the establishment of .NET 5 a deprecated technology.
- The following use cases are to be considered
  - UI using WPF / WinForms: Future is .NET Core 3.1 and .NET 5 => user should migrate there
  - UI using Xamarin.Forms / Xamarin / System.Maui => users are already at `netstandard2.1` and .NET 5 (Mono + CoreCLR)
  - Service / Web Interface for remote controlling  => .NET Core 3.1
  - Console => Users are already on .NET Core 3.1

**Comment by tthiery** [comment]
@dlech Since you are anyway watching ... would you be interested in doing code reviews?

I understand if you prefer not, since you look like a busy man ;)

**Comment by dlech** [comment]
I can't review everything, but maybe occasionally. I don't do much with C# these days, but I really like the language and would like to do a little something to keep up with.

**Comment by tthiery** [comment]
Then I will start doing feature branches / pull requests and ping you. If you do not reply like in a day or two, I will just go ahead.
