### ISSUE TITLE
Add Xamarin support

### ISSUE THREAD

**Issue by tthiery** [sharpbrick/powered-up#69]
- [ ] Find right abstraction library
- [ ] Create assembly for hosting it
- [ ] Create sample app (not in the library project)

**Comment by Berdsen** [comment]
Hi,
I recently started to write a [lego boost xamarin library](https://github.com/Berdsen/lego-boost-xamarin)  when I found this awesome project. So I forked it and implemented the Xamarin Bluetooth implementation (based on Plugin.BLE) to be able to use the core lib within xamarin.

I would like to pull reques, but I have some questions. You recently updated the project to .NET 5 but this will be incompatible with Xamarin (Forms). I reworked it already in my feature branch (use latest c# version, targetFramework netstandard2.1).

But maybe a better solution would be to have two solution files with one Windows and one Xamarin projects?
Shall I open the pull request to discuss this within the pr itself?

**Comment by tthiery** [comment]
Damn. What a unfortunate moment. A months earlier and I would have delayed the whole new tech wave till after .NET 6.

I think the best option is:

- we create a maintenance release on the 3.x version which will support Xamarin.Forms 5.
- we stabilize the whole feature there
- with .NET 6 in November we merge the stuff in the v4+ at that time

Is that acceptable to you? It would lock you out of the mainline for 8+ months. Which is endless and super short at the same time. The other alternatives are duplicate implementions (like suggested but I do not like it) or some magic on the project files and #ifdefs.

I want your contribution!! We just need to find the right way of doing it.

Create the pull so I can have a look. that does not harm!
