### ISSUE TITLE
Breaking Code Cleanup (v1.0)

### ISSUE THREAD

**Issue by tthiery** [sharpbrick/powered-up#8]
- [X] Enum according to .NET Guidelines (flags plural, all other singular)
- [X] Enums of messages into global namespace (since also used by Functions, Devices, ..)
- [x] unit clarifications of all parameters (e.g. timeInMs)
- [ ] remove abbreviations
- [x] add documentation 
- [x] cleanup namespaces to allow regular users to only include one namespace
  - [X] Remove Devices and Hub Namespace
  - [X] Move Knowledge back into Protocol namespace
  - [X] Move shared usage enums into root namespace

**Comment by Mattze0815** [comment]
Hi tthiery,
I didn't know how to contact you. I would like to participate, how can we get in touch? I am working on a quite complex LEGO train automation project and would like to check if we can collaborate. My e-mail is info@mattzobricks.com.

Sorry for the comment here. After you have dropped me an e-mail, you may delete it.

Thanks!

Mattze
